/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BooleanField: typeof import('./src/components/field-renderers/BooleanField.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    CardView: typeof import('./src/components/CardView.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ContactField: typeof import('./src/components/field-renderers/ContactField.vue')['default']
    DateField: typeof import('./src/components/field-renderers/DateField.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EmptyState: typeof import('./src/components/EmptyState.vue')['default']
    ErrorDisplay: typeof import('./src/components/ErrorDisplay.vue')['default']
    FileField: typeof import('./src/components/field-renderers/FileField.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    FormFields: typeof import('./src/components/FormFields.vue')['default']
    HeaderView: typeof import('./src/components/HeaderView.vue')['default']
    IconButton: typeof import('./src/components/IconButton.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ListView: typeof import('./src/components/ListView.vue')['default']
    LoadingSkeleton: typeof import('./src/components/LoadingSkeleton.vue')['default']
    LoadMoreButton: typeof import('./src/components/LoadMoreButton.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NumbersField: typeof import('./src/components/field-renderers/NumbersField.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RichTextField: typeof import('./src/components/field-renderers/RichTextField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilterSkeleton: typeof import('./src/components/SearchFilterSkeleton.vue')['default']
    SelectField: typeof import('./src/components/field-renderers/SelectField.vue')['default']
    TableView: typeof import('./src/components/TableView.vue')['default']
    TemplateEditor: typeof import('./src/components/TemplateEditor.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TextField: typeof import('./src/components/field-renderers/TextField.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    UrlField: typeof import('./src/components/field-renderers/UrlField.vue')['default']
  }
}
